FROM python:3.12-alpine

SHELL ["/bin/bash", "-c"]

ONBUILD WORKDIR /app
ONBUILD COPY befunge_intepretor.py /app/befunge_intepretor.py
ONBUILD COPY ./app /app/app

ONBUILD CMD ["python3", "befunge_intepretor.py", "/app/app/main.bf"]
