FROM python:3.12-alpine

SHELL ["/bin/bash", "-c"]

WORKDIR /app
COPY befunge_intepretor.py /app/befunge_intepretor.py
COPY ./app /app/app

CMD ["python3", "befunge_intepretor.py", "/app/app/main.bf"]
