FROM maven:3.9 as builder

SHELL ["/bin/bash", "-c"]

WORKDIR /app
COPY . /app

RUN mvn dependency:resolve -f app/pom.xml \
    && mvn package -f app/pom.xml \
    && cp app/target/app.jar . \
    && rm -rf app/


FROM openjdk:21-slim

SHELL ["/bin/bash", "-c"]

COPY --from=builder /app /app

WORKDIR /app

CMD ["java", "-jar", "app.jar"]