FROM gcc:13.2

SHELL ["/bin/bash", "-c"]

ONBUILD WORKDIR /app
ONBUILD COPY /app /app

ONBUILD RUN make && make clean

ONBUILD RUN find /path/to/directory -type f ! -name 'compiled-app' -exec rm -f {} +

ONBUILD CMD ["./compiled-app"]
