- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present
  become: true

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  become: true

- name: Pull registry Docker image
  community.docker.docker_image:
    name: registry
    source: pull
    tag: "2" # This is the version used on the docs
  become: true

# Based on the docs command
# docker run -d -p 5000:5000 --restart=always --name registry registry:2
- name: Create a docker registry container
  community.docker.docker_container:
    detach: true # -d
    published_ports: 5000:5000 # -p
    restart_policy: always # --restart
    name: registry # --name
    image: registry:2
  become: true