apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-deployment # Must be replace
  namespace: default
spec:
  replicas: 1 # Configurable
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: nginx:latest # Must be replace
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 80 # Configurable
        resources: # Configurable
          limits:
            cpu: 250m
            memory: 64Mi
          requests:
            cpu: 250m
            memory: 64Mi
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
