apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-service # Must be replace
  namespace: default
spec:
  ports: # Configurable
  - port: 8080
    targetPort: 80
  selector:
    app: app
  type: LoadBalancer
