apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: nginx:latest
        name: redis
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 64Mi
          requests:
            cpu: 250m
            memory: 64Mi
      restartPolicy: Always
