apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-service
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: redis
  type: LoadBalancer
