# https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

- name: Add Kubectl GPG Key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    state: present
  become: true

- name: Add kubectl package source
  apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
    state: present
  become: true

- name: Update apt and install kubectl
  ansible.builtin.apt:
    update_cache: yes
    state: present
    pkg:
      - kubectl
  become: true

- name: Install yaml python module
  ansible.builtin.apt:
    update_cache: yes
    state: present
    pkg:
      - python3-yaml
  become: true

- name: Copy app.deployement.yaml
  ansible.builtin.copy:
    src: ../files/app.deployment.yaml
    dest: /opt/app.deployment.yaml
    mode: '600'
    owner: jenkins
    group: jenkins
  become: true

- name: Copy app.service.yaml
  ansible.builtin.copy:
    src: ../files/app.service.yaml
    dest: /opt/app.service.yaml
    mode: '600'
    owner: jenkins
    group: jenkins
  become: true

- name: Copy replaceVar.py
  ansible.builtin.copy:
    src: ../files/replaceVar.py
    dest: /opt/replaceVar.py
    mode: '600'
    owner: jenkins
    group: jenkins
  become: true