jenkins:
  systemMessage: "Welcome to Jenkins!"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "Admin"
          name: "Admin"
          password: "${ADMIN_PASSWORD}"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "Admin"
            description: "Administrator role"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "Admin"
unclassified:
  location:
    url: http://127.0.0.1:8080/

jobs:
  - file: "/usr/local/job_dsl.groovy"