- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present
  become: true

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    update_cache: yes
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  become: true

- name: Add the docker group to jenkins user
  ansible.builtin.user:
    append: true
    groups: docker
    name: jenkins
  become: true
  register: add_docker_group

- name: Unconditionally reboot the machine with all defaults
  ansible.builtin.reboot:
  become: true
  when: add_docker_group is changed

- name: ReStart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true
  when: add_docker_group is changed

- name: Log into DockerHub
  docker_login:
    username: "{{ DOCKER_USERNAME }}"
    password: "{{ DOCKER_PASSWORD }}"
  become: true
  become_user: jenkins

- name: Copy Docker registry info
  ansible.builtin.template:
    src: ../files/registryInfo
    dest: /opt/registryInfo
    mode: '600'
    owner: jenkins
    group: jenkins
  become: true