- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present
  become: true

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    update_cache: yes
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  become: true

- name: Add the docker group to jenkins user
  ansible.builtin.user:
    append: true
    groups: docker
    name: jenkins
  become: true

- name: ReStart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true

- name: Log into DockerHub
  ansible.builtin.shell:
    cmd: "docker login -u {{ DOCKER_USERNAME }} -p {{ DOCKER_PASSWORD }}"
    chdir: /var/lib/jenkins
  become: true
  become_user: jenkins

- name: Setup docker permission
  ansible.builtin.file:
    path: /var/run/docker.sock
    mode: 666
  become: true

- name: Copy Docker registry info
  ansible.builtin.template:
    src: ../files/registryInfo
    dest: /var/lib/jenkins/registryInfo
    mode: u=rw,g=r,o=r
  become: true
  become_user: jenkins