FROM python:3.12-alpine

SHELL ["/bin/bash", "-c"]

ONBUILD WORKDIR /app
ONBUILD COPY . /app

ONBUILD COPY requirements.txt .

ONBUILD RUN pip install -r requirements.txt

ONBUILD CMD ["python", "-m", "app"]