FROM node:20.9

SHELL ["/bin/bash", "-c"]

ONBUILD WORKDIR /app

ONBUILD COPY package.json .

ONBUILD COPY package-lock.json .

ONBUILD RUN ["npm", "install"]

ONBUILD COPY . .

ONBUILD CMD ["node", "."]